name: Bug Report
description: Submit a bug to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Android patcher software name and version
      placeholder: Like duolingo-v1.2.3
    validations:
      required: true

  - type: input
    id: target-version
    attributes:
      label: Target software version
      placeholder: Like v5.6.7
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Reproduce steps
      placeholder: |
        1. Click ...
        2. Click ...
        3. See the bug
    validations:
      required: true

  - type: textarea
    id: expected-and-actual
    attributes:
      label: Expected behavior and actual behavior
    validations:
      required: true